config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'chatroom', to: 'chatroom#index'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  # A single call to resources can declare all of the necessary routes for your index,
  #    show, new, edit, create, update, and destroy actions.
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'

  # ================================================================================================
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { minimum: 1, maximum: 100 }
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :messages, dependent: :destroy

  validates :username, presence: true,
              uniqueness: { case_sensitive: false }, 
              length: { minimum: 3, maximum: 15 }
  validates :password, presence: true,
              length: { minimum: 6 },
              if: -> { new_record? || !password.nil? }
  validates :password_confirmation, presence: true,
              if: -> { new_record? || !password.nil? }
  validate :passwords_match

  private

  def passwords_match
    errors.add(:password_confirmation, "doesn't match Password") if password != password_confirmation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # METHODS HERE AVAILABLE ONLY TO CONTROLLERS unless helper_method is used

  helper_method :current_user, :logged_in?

  def current_user
    # memoization
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # returns true or false
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      # calls app/javascript/channels/chatroom_channel.js :: received
      ActionCable.server.broadcast "chatroom_channel", { mod_message: message_render(message) }
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create] 

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      flash[:success] = "Logged in successfully"
      redirect_to chatroom_path
    else
      flash.now[:error] = "There was something wrong with your login details"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to chatroom_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id    # log the user in
      flash[:success] = "Welcome to the MessageMe!"
      redirect_to chatroom_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private 

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular orange coffee icon"></i>
  Say something
</h2>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div class="ui feed" id="message-container">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
                    <div class="field">
                        <div class="ui fluid icon input">
                            <%= f.text_field :body, placeholder: "Enter a message..." %>
                            <%= f.button '<i class="large orange paper plane icon"></i>'.html_safe %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui inverted vertical menu">
                    <a class="active item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %> 

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", chatroom_path, class: "item" %>
<a class="item">
    Messages
</a>
<div class="right menu">
    <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
            <% if logged_in? %>
                <%= link_to "Log out", logout_path, class: "item", data:{ "turbo-method": :delete } %>
            <% else %>
                <%= link_to "Log in", login_path, class: "item" %>
                <%= link_to "Sign up", signup_path, class: "item" %>
            <% end %>
        </div>
    </div>
    <% if !logged_in? %>
        <div class="item">
            <%= link_to "Log in", login_path, class: "ui primary button" %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation'%>
      </div>
    </div>

    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <a><%= message.user.username %></a>: <%= message.body %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div class="ui error message transition">
        <i class="close icon"></i>
        <div class="header">
            <h4>Please fix the following errors</h4>
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
</div>
<% end %>

<h2 class="ui center aligned large header">Welcome to MessageMe - <em>a complete Chat App</em></h2>

<h4 class="ui center aligned icon header">
  <i class="circular orange power off icon"></i>
  Sign up
</h4>

<div class="ui placeholder segment">
  <div class="ui very relaxed stackable grid">
    <div class="column">
        <%= form_for(:user, html: {class: "ui form", role: "form"}, url: signup_path) do |f| %>
            <div class="field">
                <%= f.label :username, "Username" %>
                <div class="ui left icon input">
                <%= f.text_field :username, placeholder: "Username" %>
                <i class="user icon"></i>
                </div>
            </div>
            <div class="field">
                <%= f.label :password, "Password" %>
                <div class="ui left icon input">
                    <%= f.password_field :password, placeholder: "Password" %>
                    <i class="lock icon"></i>
                </div>
            </div>
            <div class="field">
                <%= f.label :password_confirmation, "Confirm Password" %>
                <div class="ui left icon input">
                    <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
                    <i class="lock icon"></i>
                </div>
            </div>
            <%= f.button "Sign Up", class: "ui orange submit button" %>
        <% end %>
    </div>
  </div>
</div>